# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conoha < Formula
  desc "CLI tool for ConoHa VPS3 API"
  homepage "https://crowdy.github.io/conoha-cli-pages/"
  version "0.4.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crowdy/conoha-cli/releases/download/v0.4.4/conoha-cli_0.4.4_darwin_amd64.tar.gz"
      sha256 "f68e71f8500a27cd52760f2e9287801b9f8d110d017d4dba7a816bb29ef8a7c3"

      define_method(:install) do
        bin.install "conoha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crowdy/conoha-cli/releases/download/v0.4.4/conoha-cli_0.4.4_darwin_arm64.tar.gz"
      sha256 "ec064d8a50d52f6b46ea44ab8d0d668f228392184e8906b168a743dfca910211"

      define_method(:install) do
        bin.install "conoha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crowdy/conoha-cli/releases/download/v0.4.4/conoha-cli_0.4.4_linux_amd64.tar.gz"
      sha256 "1a8351cec1d80070dc88f844ab4a64604b6f02248c9741f3d964a9d9bbc01111"
      define_method(:install) do
        bin.install "conoha"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crowdy/conoha-cli/releases/download/v0.4.4/conoha-cli_0.4.4_linux_arm64.tar.gz"
      sha256 "fed00cc533cc092d533fef5ccac3b8cb9bf7f122f0808c977ea8aa8f06c17448"
      define_method(:install) do
        bin.install "conoha"
      end
    end
  end
end
