# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conoha < Formula
  desc "CLI tool for ConoHa VPS3 API"
  homepage "https://crowdy.github.io/conoha-cli-pages/"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crowdy/conoha-cli/releases/download/v0.5.0/conoha-cli_0.5.0_darwin_amd64.tar.gz"
      sha256 "94e50cb52896a1d6978ae258c28665c09c37631f0021f716c594e02edc07590b"

      define_method(:install) do
        bin.install "conoha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crowdy/conoha-cli/releases/download/v0.5.0/conoha-cli_0.5.0_darwin_arm64.tar.gz"
      sha256 "0a7c344e9f9ba34fd856e37b7c8b9d0911775d557fba6fc9344a4332e350615c"

      define_method(:install) do
        bin.install "conoha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crowdy/conoha-cli/releases/download/v0.5.0/conoha-cli_0.5.0_linux_amd64.tar.gz"
      sha256 "cd2b927e62650f60d37d76b343856c1d7f96c318038063ca816cf8aca2ca5383"
      define_method(:install) do
        bin.install "conoha"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crowdy/conoha-cli/releases/download/v0.5.0/conoha-cli_0.5.0_linux_arm64.tar.gz"
      sha256 "ab18021abdada0ce025c3d04084bcb2374ecce8daebc34e7b42a016729b79104"
      define_method(:install) do
        bin.install "conoha"
      end
    end
  end
end
